### ISSUE TITLE
Not able to call Logback directly

### ISSUE THREAD

**Issue by rohit-gandhe** [jlib-framework/jlib-awslambda-logback#1]
Just using those two dependencies, I am not able to import Logback classes directly

`
import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
`

I want to be able to set the root logger's log level from code in order to change it dynamically by reading the lambda environment variable. This allows me to change the level by just saving the lambda instead of deploying it.

**Comment by igorakkerman** [comment]
Thanks for using this library.

In order to access the Logback classes at compile time, you can change the dependency scope from _runtime_ to _compile_:

Gradle:
```
implementation 'org.jlib:jlib-awslambda-logback:1.0.0'
```    

Maven (compile scope is the default):
```    
<dependency>
    <groupId>org.jlib</groupId>
    <artifactId>jlib-awslambda-logback</artifactId>
    <version>1.0.0</version>
</dependency>
```
